# Name - Neeraj Joshi
# Roll No - 120
# SAP - 500076568
# AIML (Batch - 4)
# Sem 5
# Experiment - 2

### Performing Pandas and Numpy Operations

In [ ]:
import pandas as pd

In [2]:
#creating the dataframe

data = [['tom', 36 , 'US'], ['nick', 25 , 'Spain'], ['juli', 54 , 'Italy'], ['Alan', 25 , 'Spain'], ['nick', 35 , 'US'] ]

df = pd.DataFrame(data, columns = ['Name', 'Age', 'Country'])

df

Name  Age Country
0   tom   36      US
1  nick   25   Spain
2  juli   54   Italy
3  Alan   25   Spain
4  nick   35      US

In [3]:
#converting the dataframe to csv
df.to_csv('info.csv')

In [4]:
#index and columns in dataset
print(df.index , end = "\n\n") 
print(df.columns , end = "\n\n")

RangeIndex(start=0, stop=5, step=1)

Index(['Name', 'Age', 'Country'], dtype='object')



In [5]:
#different datatypes in dataset
print(df.dtypes , end = "\n\n")

Name       object
Age         int64
Country    object
dtype: object



In [6]:
#sorting the data with respect to index 
df.sort_index(axis = 0 , ascending = False)

Name  Age Country
4  nick   35      US
3  Alan   25   Spain
2  juli   54   Italy
1  nick   25   Spain
0   tom   36      US

In [7]:
#sorting the data with respect to columns
df.sort_index(axis = 1 , ascending = False)

Name Country  Age
0   tom      US   36
1  nick   Spain   25
2  juli   Italy   54
3  Alan   Spain   25
4  nick      US   35

In [8]:
#printing specific values using loc function
df.loc[(df['Age']>30)]

Name  Age Country
0   tom   36      US
2  juli   54   Italy
4  nick   35      US

In [9]:
#removing same values in a specific column
df = df.drop_duplicates(subset = ['Name'])
df

Name  Age Country
0   tom   36      US
1  nick   25   Spain
2  juli   54   Italy
3  Alan   25   Spain

In [10]:
#info of the dataset 
print(df.info)
print(df.describe)

<bound method DataFrame.info of    Name  Age Country
0   tom   36      US
1  nick   25   Spain
2  juli   54   Italy
3  Alan   25   Spain>
<bound method NDFrame.describe of    Name  Age Country
0   tom   36      US
1  nick   25   Spain
2  juli   54   Italy
3  Alan   25   Spain>


In [11]:
#Different countries listed in the dataset
df['Country'].value_counts

<bound method IndexOpsMixin.value_counts of 0       US
1    Spain
2    Italy
3    Spain
Name: Country, dtype: object>

In [12]:
#using groupby function
df.groupby('Country').Age.max()

Country
Italy    54
Spain    25
US       36
Name: Age, dtype: int64

In [13]:
#isnull function
df[pd.isnull]

Name  Age Country
0  NaN  NaN     NaN
1  NaN  NaN     NaN
2  NaN  NaN     NaN
3  NaN  NaN     NaN

In [14]:
#getting various mathematical values 
df.describe()

Age
count   4.000000
mean   35.000000
std    13.686977
min    25.000000
25%    25.000000
50%    30.500000
75%    40.500000
max    54.000000

In [15]:
#concatenating dataframs
df_1 = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
df_2 = pd.DataFrame({'col3': [5, 6], 'col4': [7, 8]})

pd.concat([df_1 , df_2] , axis = 1)

col1  col2  col3  col4
0     1     3     5     7
1     2     4     6     8

In [16]:
#using select_dtypes
df.select_dtypes(include='object')

Name Country
0   tom      US
1  nick   Spain
2  juli   Italy
3  Alan   Spain

# NUMPY

In [1]:
import numpy as np

In [2]:
#creating 2D array  
arr = np.array([[1 ,3 ,5 ,6] , [12, 5 ,3 ,1] , [6, 87, 32, 9]])
arr

array([[ 1,  3,  5,  6],
       [12,  5,  3,  1],
       [ 6, 87, 32,  9]])

In [3]:
#slicing the array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [5]:
#concatenating
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
#getting datatypes
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [8]:
#Stacking along rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [9]:
#splitting the array
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [10]:
#searching , returns indexes
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [11]:
#searchsorted function
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [12]:
#sorting
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [22]:
#generating random number using numpy
from numpy import random
x = random.randint(100)
print(x)

21


In [13]:
#filter function
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [14]:
#getting dimension
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d.ndim)

3


In [16]:
#creating a copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
print(x)

[1 2 3 4 5]


In [19]:
#Generate Random Array
x = random.randint(100, size=(5))
print(x)

[ 0 23 23 26 59]


In [21]:
#creating array with random values containing 3 rows with 5 elements
x = random.randint(100, size=(3, 5))
print(x)

[[93 71 27 70 54]
 [17 38 48 14  0]
 [67  3 41 71 46]]
