MULTI LINEAR REGRESSION

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprice.csv")

In [3]:
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  620000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.Bedrooms = df.Bedrooms.fillna(df.Bedrooms.median())
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  620000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
model = linear_model.LinearRegression()

model.fit(df.drop('Price', axis='columns') , df.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
model.coef_

array([  107.54695607, 27066.74672044, -2875.62966823])

In [7]:
model.intercept_

217217.6782895684

In [8]:
model.predict([[3000, 3, 40]])

array([506033.5999275])

Save Model To a File Using Python Pickle

In [9]:
import pickle

In [10]:
with open('model_pickle','wb') as file :
    
    pickle.dump(model,file)

Load Saved Model

In [11]:
with open('model_pickle','rb') as file :
    
    mp = pickle.load(file)

In [12]:
mp.coef_

array([  107.54695607, 27066.74672044, -2875.62966823])

In [13]:
mp.intercept_

217217.6782895684

In [14]:
mp.predict([[3000, 3, 40]])

array([506033.5999275])

Save Trained Model Using joblib

In [15]:
from sklearn.externals import joblib

D:\ANACONDA\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [16]:
joblib.dump(model, 'model_joblib')

['model_joblib']

Load Saved Model

In [17]:
mj = joblib.load('model_joblib')

In [18]:
mj.coef_

array([  107.54695607, 27066.74672044, -2875.62966823])

In [19]:
mj.predict([[3000, 3, 40]])

array([506033.5999275])